# Generated by Django 3.0 on 2020-05-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('logo', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('employee_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('code', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('picture', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('skills', models.CharField(default='no skills required', max_length=64)),
                ('description', models.CharField(max_length=1000)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('published_at', models.DateTimeField()),
                ('company', models.ForeignKey(default='some company', on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='djumanji.Company')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='djumanji.Speciality')),
            ],
        ),
    ]
