# Generated by Django 3.0 on 2020-06-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djumanji', '0002_educationchoices_gradechoices_specialtychoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='education_choices',
            field=models.ManyToManyField(default='Не выбрано', related_name='EducationChoices', to='djumanji.EducationChoices'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='grade_choices',
            field=models.ManyToManyField(default='Не выбрано', related_name='GradeChoices', to='djumanji.GradeChoices'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='speciality_choices',
            field=models.ManyToManyField(default='Не выбрано', related_name='SpecialityChoices', to='djumanji.SpecialtyChoices'),
        ),
    ]
