# Generated by Django 3.0 on 2020-06-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djumanji', '0003_auto_20200603_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='education_choices',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='grade_choices',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='speciality_choices',
        ),
        migrations.DeleteModel(
            name='EducationChoices',
        ),
        migrations.DeleteModel(
            name='GradeChoices',
        ),
        migrations.DeleteModel(
            name='SpecialtyChoices',
        ),
    ]
